---
title: "January Meetup Recap: What We Learned at rstudio::conf"
author: "Angela Li"
date: "`r format(Sys.Date())`"
output: html_document
categories: ["R"]
tags: ["rladies","chicago"]
---

For our [January R-Ladies Chicago Meetup](https://www.meetup.com/rladies-chicago/events/257346957/), five Chicago R-Ladies presented lightning talks on topics they learned about at rstudio::conf 2019. Three of our organizers attended workshops on diversity scholarships, so we were especially excited to hear what they learned. Natalie Jorion also volunteered to speak, and we ended up having a total of five speakers! Each person spoke for 10 minutes on a subject they thought was interesting. 

Topics of the night included deep learning, improving data project organization, tips for Shiny applications, reproducible research, and contributing to open source. 

First, [Caroline Williams](https://twitter.com/ckwill36) told us what she learned at the deep learning in R workshop. Her slides can be found [here](https://docs.google.com/presentation/d/1HZBv5TmzP6oQkZthnmw3GfK1fN1TYQjM-F11qvoFQgo/edit#slide=id.p).

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Our <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> lighting talks are starting with <a href="https://twitter.com/ckwill36?ref_src=twsrc%5Etfw">@ckwill36</a> discussing deep learning <a href="https://t.co/Z85sg0IT2p">pic.twitter.com/Z85sg0IT2p</a></p>&mdash; R-Ladies Chicago (@RLadiesChicago) <a href="https://twitter.com/RLadiesChicago/status/1090046174252462080?ref_src=twsrc%5Etfw">January 29, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Next, [Amy Yang](https://twitter.com/ayanalytics) explained how to properly write file paths in R. Her slides can be found [here](https://docs.google.com/presentation/d/1c7sNVqVByTia57IhK1Uux6zrVrbpnWJuLT9LAFf2uh4/).

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ayanalytics?ref_src=twsrc%5Etfw">@ayanalytics</a> relaying <a href="https://twitter.com/JennyBryan?ref_src=twsrc%5Etfw">@JennyBryan</a>’s legendary advice about file paths to <a href="https://twitter.com/hashtag/RLadies?src=hash&amp;ref_src=twsrc%5Etfw">#RLadies</a> Chicago. <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> ⚡️talks <a href="https://t.co/jh4mJknTCW">pic.twitter.com/jh4mJknTCW</a></p>&mdash; R-Ladies Chicago (@RLadiesChicago) <a href="https://twitter.com/RLadiesChicago/status/1090050001148018689?ref_src=twsrc%5Etfw">January 29, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

After that, [Natalie Jorion](https://www.linkedin.com/in/njorion/) gave us 10 tips for making better Shiny apps. Her slides can be found [here](https://docs.google.com/presentation/d/1CD0PMnWAcjau7fzIcXDooiIdjpvDQCCqXr0edkySwxk/edit).

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Natalie Jorion gives us some protips for Shiny apps! <a href="https://twitter.com/hashtag/RLadies?src=hash&amp;ref_src=twsrc%5Etfw">#RLadies</a> <a href="https://twitter.com/hashtag/RStudioConf?src=hash&amp;ref_src=twsrc%5Etfw">#RStudioConf</a> ⚡️talks <a href="https://t.co/gKyr3qx6vY">pic.twitter.com/gKyr3qx6vY</a></p>&mdash; R-Ladies Chicago (@RLadiesChicago) <a href="https://twitter.com/RLadiesChicago/status/1090052135536992259?ref_src=twsrc%5Etfw">January 29, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Following that, [Katherine Simeon](https://katherinesimeon.github.io/) presented on what she learned about conducting reproducible research in R. Her ([xaringan!](https://bookdown.org/yihui/rmarkdown/xaringan.html)) slides can be found [here](https://katherinesimeon.github.io/20190128-reproducible-research/#1).

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">New packages introduced by <a href="https://twitter.com/kitkatbar429?ref_src=twsrc%5Etfw">@kitkatbar429</a> in her reproducible research talk following up <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> include: usethis, rrtools, containerit, and “Knit with Parameters” in <a href="https://twitter.com/hashtag/rmarkdown?src=hash&amp;ref_src=twsrc%5Etfw">#rmarkdown</a> <a href="https://t.co/rg1PMlXbDi">pic.twitter.com/rg1PMlXbDi</a></p>&mdash; R-Ladies Chicago (@RLadiesChicago) <a href="https://twitter.com/RLadiesChicago/status/1090056012718059520?ref_src=twsrc%5Etfw">January 29, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Finally, I talked about my experience contributing to open source at Tidyverse Developer Day. My slides can be found [here](https://docs.google.com/presentation/d/1iodn7rsklI1wryld-NN_Dslr7tHM0xyoMx2C3RRFTJc/).

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/CivicAngela?ref_src=twsrc%5Etfw">@CivicAngela</a> tells us about submitting a pull request during <a href="https://twitter.com/hashtag/TidyverseDevDay?src=hash&amp;ref_src=twsrc%5Etfw">#TidyverseDevDay</a>. 💪🏼 <a href="https://twitter.com/hashtag/RLadies?src=hash&amp;ref_src=twsrc%5Etfw">#RLadies</a> <a href="https://t.co/uttH5w3rlY">pic.twitter.com/uttH5w3rlY</a></p>&mdash; R-Ladies Chicago (@RLadiesChicago) <a href="https://twitter.com/RLadiesChicago/status/1090058635508633602?ref_src=twsrc%5Etfw">January 29, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

I thought the lightning talk format where each person spoke for 5-10 minutes was a nice way to cover many different topics at once, and I was impressed at how many people braved the sub-zero weather and the snow to come to the Meetup! Thank you [WeWork Kinzie](https://www.wework.com/buildings/20-w-kinzie-st--chicago--IL) for hosting us and keeping us warm at the Meetup, and [Microsoft](https://developer.microsoft.com/en-us/advocates/index.html) for food as always.

## Additional Reading

- [Florencia Mangini](https://twitter.com/manginiflor) put together a lovely detailed recap of the event with more links to things we mentioned in our presentations, which you can read at [her blog](http://www.thinkingondata.com/r-ladies-chicago-what-we-learned-at-rstudioconf-2019-lightning-talks/)!
